name: Run Web Crawler

on:
  workflow_dispatch:    # 手動執行
  schedule:             # 每天執行一次（UTC 時間）
    - cron: '0 0 * * *' # 每天 00:00 UTC（台灣是早上 8:00）

jobs:
  run-crawlers:
    runs-on: ubuntu-latest

    steps:
    - name: 下載程式碼
      uses: actions/checkout@v3

    - name: 安裝 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安裝套件
      run: |
        pip install requests beautifulsoup4

    - name: 執行 static.py
      run: python static.py

    - name: 執行 api.py
      run: python api.py

    - name: 上傳輸出檔案
      uses: actions/upload-artifact@v2
      with:
        name: crawler-results
        path: |
          ./static.csv
          ./static.json
          ./api.csv